WIP: SearchAnswer lookup to look at option values instead of slugs
projectcaluma/caluma pull request #1281
Opened 2020-11-20 12:44 UTC by winged

This is a WIP prototype / idea that came out of a discussion in a customer project. Not ready to merge at all, just making a PR for a potential discussion around this

2020-12-17 07:02 UTC, open-dynaMIX requested changes
NIce work! :tada:

Just two nitpicks.

Technically this should be considered a breaking change, right?

2020-12-17 08:57 UTC, winged commented on docker-compose.yml
> +    image: postgres:10.15-alpine
This was part of a conflict resolution and shouldn't be here in the first place

2020-12-17 08:57 UTC, winged commented on caluma/caluma_form/filters.py
> +        ):
You're right, fixed

2020-12-17 10:25 UTC, winged commented
> Technically this should be considered a breaking change, right?

I thought about this as well. Technically, searching choice fields never worked correctly, anyway: The option slug often only "accidentally" matches the displayed value, especially in multilingual environments. So we could even think of that part as a "fix" instead. And Multiple Choice wasn't supported before either :-)

2020-12-17 10:31 UTC, open-dynaMIX commented
> So we could even think of that part as a "fix" instead

Fair enough!

2020-12-17 10:31 UTC, open-dynaMIX approved these changes

2020-12-17 10:31 UTC, merged

2020-12-18 07:12 UTC, czosel commented
Hmm, if I’m not mistaken this is very much a breaking change. We implement search in choice questions usually using dropdowns where the key is the option slug. This would probably break most of those. Cc @anehx

2020-12-18 08:23 UTC, winged commented
> Hmm, if I’m not mistaken this is very much a breaking change. We implement search in choice questions usually using dropdowns where the key is the option slug. This would probably break most of those. Cc @anehx

But do you use the `searchAnswers` filter for this case, or the more suitable `hasAnswer` one`? For strict lookups like when using dropdowns, the latter should be preferred anyway, as the search filter defaults to infix, which in turn could also return slugs that are superstring (opposite of substring??) of the requested one (Think `foo-bar` and `foo-bar-baz`, which would both be returned if you select `foo-bar`)

2020-12-18 10:14 UTC, czosel commented
Ah right, seems that we're using `hasAnswer` in those cases. Thanks!