Fix creating documents
projectcaluma/caluma pull request #1288
Opened 2020-11-23 16:03 UTC by open-dynaMIX

2020-11-23 16:24 UTC, open-dynaMIX commented
/cc @anehx

2020-11-25 08:01 UTC, anehx requested changes

2020-11-25 08:01 UTC, anehx commented on caluma/caluma_form/domain_logic.py
> +                        question.row_form, document
I think you mean `sub_form`

2020-11-25 08:27 UTC, open-dynaMIX commented on caluma/caluma_form/domain_logic.py
> +                        question.row_form, document
Yes, fixed.

2020-11-25 08:28 UTC, open-dynaMIX commented on caluma/caluma_form/domain_logic.py
> +                for row_doc in new_answer.documents.iterator():
Changed.

2020-11-25 08:33 UTC, anehx approved these changes

2020-11-25 09:00 UTC, merged