feat(analytics): introduce analytics table
projectcaluma/caluma pull request #1572
Opened 2021-10-08 13:43 UTC by winged

The analytics table provides insight into Caluma's data by collecting
information from forms, cases, and so on.

2021-11-16 09:22 UTC, derrabauke commented
Found another issue. When queryieng the backend for records via:
```graphql
query getTableData {
  analyticsTable (slug: "SomeExistingSlug") {
    resultData {
      ...ResultData
    }
  }
}
``` 
I get an error message in the resulting data:
```json
{
  "errors": [
    {
      "message": "int() argument must be a string, a bytes-like object or a number, not 'NoneType'",
      "locations": [
        {
          "line": 130,
          "column": 3
        }
      ],
      "path": [
        "analyticsTable",
        "resultData",
        "records"
      ]
    }
  ],
  "data": {
    "analyticsTable": {
      "resultData": {
        "records": null
      }
    }
  }
}
```
Might be some incomplete implementation, which is normal for WIP, but wanted to state this somehow.

2022-01-24 15:23 UTC, winged commented
@fugal-dy @open-dynaMIX @czosel ready for review

2022-02-07 10:51 UTC, open-dynaMIX requested changes
Awesome work!!! :rocket:

2022-02-07 10:51 UTC, open-dynaMIX commented on caluma/caluma_analytics/simple_table.py
> +class FormAnswerField(AttributeField):
Consider renaming to `DocumentAnswerField`.

2022-02-07 10:51 UTC, open-dynaMIX commented on caluma/caluma_analytics/simple_table.py
> +        return {}
Duplicated code. See `AttributeField`.

2022-02-07 10:51 UTC, open-dynaMIX commented on caluma/caluma_analytics/sql.py
> +                # hacky SQL_INJECTION_PRONE FIRST ATTEMPT
Leftover comment.

2022-02-07 10:51 UTC, open-dynaMIX commented on caluma/caluma_analytics/sql.py
> +        else:
`else` not needed.

2022-02-07 10:51 UTC, open-dynaMIX commented on caluma/caluma_analytics/tests/test_form_field_extraction.py
> +    print(table.last_query)
Leftover print statement

2022-02-07 10:51 UTC, open-dynaMIX commented on caluma/caluma_analytics/tests/test_simple_table.py
> +    # TODO: re-add document fields once tings are stabilized
Unfinished TODO.

2022-02-07 10:51 UTC, open-dynaMIX commented on caluma/caluma_analytics/tests/test_table.py
> +    assert result.errors
Please assert that the right error happened.

2022-02-07 10:51 UTC, open-dynaMIX commented on caluma/caluma_analytics/tests/test_table.py
> +    assert result.errors
Please assert that the right error happened.

2022-02-10 11:52 UTC, winged commented
Weird - Don't know why all those snapshots disappeared. Investigating...

2022-02-11 11:32 UTC, merged

2022-02-11 11:33 UTC, winged commented
Merged as per today's discussion :-)