feat: Expose more CORS related configurations via environment variables
projectcaluma/caluma pull request #1604
Opened 2021-10-29 14:31 UTC by SaschaPWittwer

With the current django configurations exposed, it was not possible to deploy and use caluma in a CORS scenario. 
With this change more CORS header configurations are exposed via environment variables. Furthermore it enhances the django default values with some caluma required stuff like the language header.

2021-11-01 08:24 UTC, anehx commented
Now the CI is failing because of the linter. Please run `docker-compose exec caluma black .`

2021-11-01 08:27 UTC, open-dynaMIX commented on caluma/settings/django.py
> +    'PUT'
Sorry to intervene. Actually we use GET requests for the `/healthz` endpoint.

2021-11-01 08:28 UTC, anehx commented on caluma/settings/django.py
> +    'PUT'
Ah right I forgot about that! Sorry @SaschaPWittwer !

2021-11-03 17:08 UTC, SaschaPWittwer commented on caluma/settings/django.py
> +    'PUT'
Ahhh good one! I will update the default value once again.

2021-11-03 19:05 UTC, anehx approved these changes

2021-11-03 19:05 UTC, anehx commented
@open-dynaMIX could you review this once again?

2021-11-04 06:32 UTC, open-dynaMIX approved these changes
Awesome, thanks a lot! :tada:

2021-11-04 06:39 UTC, open-dynaMIX requested changes
Sorry, forgot to check before. @SaschaPWittwer could you please merge all thos commits into one in order to keep the history clean? Thanks a lot!

2021-11-04 08:16 UTC, anehx commented
@open-dynaMIX let's just squash..

2021-11-04 08:18 UTC, merged