feat(form): enable hint messages on questions
projectcaluma/caluma pull request #1655
Opened 2022-01-12 08:35 UTC by luytena

Add a hint text field on all question types except for
form, static and action button questions. This functionality
requires a db migration.

2022-01-12 10:08 UTC, czosel approved these changes
LGTM :+1: @winged or @open-dynaMIX, could you take a quick look as well?

2022-01-13 13:22 UTC, winged requested changes
Code generally looks good except a small cleanup. However I'm wondering what is the use of this? What's the use case of hint vs. info texts?

2022-01-13 13:22 UTC, winged commented on caluma/caluma_form/serializers.py
> +        fields = SaveQuestionSerializer.Meta.fields + ["hint_text"]
Should probably be moved to `SaveQuestionSerializer.Meta`, so you won't have to explicitly extend the fields list in every subtype

2022-01-13 13:23 UTC, winged commented on caluma/caluma_form/serializers.py
> +        fields = SaveQuestionSerializer.Meta.fields + ["hint_text"]
Ah, nevermind, needs to be this way because form, static and action buttons don't have hints

2022-01-13 13:23 UTC, winged approved these changes

2022-01-13 14:36 UTC, winged commented
Ah, ok, makes sense!

2022-01-13 14:36 UTC, merged