feat(filter): add lookup type "IN"
projectcaluma/caluma pull request #1677
Opened 2022-02-16 13:57 UTC by czosel

Two things I'm still wondering:

- `test_query_all_questions` is running a truckload of tests, but the parametrization doesn't make sense to me
-  why do we allow the same lookup types for single choice than for multiple choice? How does e.g. INTERSECTS make sense for single choice questions?

2022-02-17 07:52 UTC, winged requested changes
Nice work, just a minor nitpick for the tests

2022-02-17 07:52 UTC, winged commented on caluma/caluma_form/tests/test_filter_by_answer.py
> +          allDocuments(hasAnswer: $hasAnswer) {
Please use new-style filter syntax - this one will be removed soon.
```suggestion
          allDocuments(filter: [{hasAnswer: $hasAnswer}]) {
```

2022-02-18 11:35 UTC, winged approved these changes
Awesome work! :tada:

2022-02-18 11:36 UTC, winged commented
Looks like it needs a snapshot update, but otherwise all good!

2022-02-18 13:02 UTC, czosel commented
Fixed

2022-02-18 15:14 UTC, closed without merging