fix(graphene): write a failing test for the getRootForms query
projectcaluma/caluma pull request #1726
Opened 2022-03-22 11:17 UTC by JohnL17

2022-03-25 09:41 UTC, winged commented on caluma/caluma_form/tests/test_form.py
> +    )
You're not passing the `$slug` input variable here - is this intentional?

This causes the `slug` filter to be disregarded, causing the error.

2022-03-25 09:41 UTC, winged commented on caluma/caluma_form/tests/test_form.py
> +    )
Added a check in the filter code to avoid crash

2022-03-30 07:48 UTC, anehx requested changes
Let's keep the test generic and simple..

2022-03-30 07:48 UTC, anehx commented on caluma/caluma_form/tests/test_form.py
> +        }
Let's keep the test simple:

```suggestion
        query Form($slug: String) {
          allForms(filter: [{ slug: $slug }]) {
            totalCount
          }
        }
```

2022-03-30 07:48 UTC, anehx commented on caluma/caluma_form/tests/test_form.py
> +    form_question_factory(form=form)
```suggestion
    form_factory.create_batch(5)
```

2022-03-30 07:48 UTC, anehx commented on caluma/caluma_form/tests/test_form.py
> +):
```suggestion
def test_optional_filter(db, form_factory, question, schema_executor):
```

2022-03-30 07:48 UTC, anehx commented on caluma/caluma_form/tests/test_form.py
> +    snapshot.assert_match(result.data)
```suggestion
    assert result.data["allForms"]["totalCount"] == 5
```

2022-03-31 08:51 UTC, winged commented
@anehx Thanks for the review, applied your suggestions

2022-03-31 09:42 UTC, anehx approved these changes

2022-03-31 11:27 UTC, merged